version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: "HookHook.Backend/Dockerfile"
    ports:
      - "8080:80"
    depends_on:
      - "mongo"
    environment:
      - Mongo__Client=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/
      - Mongo__Database=${MONGO_DATABASE}
      - JwtKey=${JWTKEY}
      - Discord__ClientId=${DISCORD_CLIENTID}
      - Discord__ClientSecret=${DISCORD_CLIENTSECRET}
      - Discord__Redirect=${DISCORD_REDIRECT}
      - Discord__BotToken=${DISCORD_BOTTOKEN}
      - GitHub__Web__ClientId=${GITHUB_WEB_CLIENTID}
      - GitHub__Web__ClientSecret=${GITHUB_WEB_CLIENTSECRET}
      - GitHub__Mobile__ClientId=${GITHUB_MOBILE_CLIENTID}
      - GitHub__Mobile__ClientSecret=${GITHUB_MOBILE_CLIENTSECRET}
      - Spotify__ClientId=${SPOTIFY_CLIENTID}
      - Spotify__ClientSecret=${SPOTIFY_CLIENTSECRET}
      - Spotify__Redirect=${SPOTIFY_REDIRECT}
      - Twitch__ClientId=${TWITCH_CLIENTID}
      - Twitch__ClientSecret=${TWITCH_CLIENTSECRET}
      - Twitch__Redirect=${TWITCH_REDIRECT}
      - Twitter__ClientId=${TWITTER_CLIENTID}
      - Twitter__ClientSecret=${TWITTER_CLIENTSECRET}
      - Twitter_Redirect={TWITTER_REDIRECT}
      - Google__ClientId=${GOOGLE_CLIENTID}
      - Google__ClientSecret=${GOOGLE_CLIENTSECRET}
      - Google__ApiKey=${GOOGLE_APIKEY}
      - Google__Redirect=${GOOGLE_REDIRECT}
      - SMTP__Email=${SMTP_EMAIL}
      - SMTP__Password=${SMTP_PASSWORD}
  client_mobile:
    build:
      context: .
      dockerfile: "HookHook.Mobile/Dockerfile"
      args:
        - TWITCH_CLIENTID=${TWITCH_CLIENTID}
        - TWITCH_REDIRECT=${TWITCH_REDIRECT}
        - DISCORD_CLIENTID=${DISCORD_CLIENTID}
        - SPOTIFY_CLIENTID=${SPOTIFY_CLIENTID}
        - GITHUB_CLIENTID=${GITHUB_MOBILE_CLIENTID}
        - GOOGLE_CLIENTID=${GOOGLE_CLIENTID}
    volumes:
      - "apk:/build"
  client_web:
    build:
      context: .
      dockerfile: "HookHook.Web/Dockerfile"
      args:
        - VUE_APP_DISCORD_CLIENTID=${DISCORD_CLIENTID}
        - VUE_APP_DISCORD_REDIRECT=${DISCORD_REDIRECT}
        - VUE_APP_GITHUB_CLIENTID=${GITHUB_WEB_CLIENTID}
        - VUE_APP_SPOTIFY_CLIENTID=${SPOTIFY_CLIENTID}
        - VUE_APP_SPOTIFY_REDIRECT=${SPOTIFY_REDIRECT}
        - VUE_APP_TWITCH_CLIENTID=${TWITCH_CLIENTID}
        - VUE_APP_TWITCH_REDIRECT=${TWITCH_REDIRECT}
        - VUE_APP_TWITTER_CLIENTID=${TWITTER_CLIENTID}
        - VUE_APP_TWITTER_REDIRECT=${TWITTER_REDIRECT}
        - VUE_APP_GOOGLE_CLIENTID=${GOOGLE_CLIENTID}
    ports:
      - "8081:80"
    depends_on:
      - "server"
      - "client_mobile"
    volumes:
      - "apk:/app/mobile"
    environment:
      - BACKEND_URL=http://server:80/
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
volumes:
  apk: