name: Build Documentations

on:
  push:
    branches:
      - 'main'

jobs:
  generate-docfx-docs:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx

      - name: Install dependencies
        run: dotnet restore

      - name: DocFX Build
        working-directory: docs
        run: docfx docfx.json
        continue-on-error: false

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          force_orphan: true
          gh-pages: backend-doc
  generate-dartdoc-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'

      - run: flutter pub get

      - name: Install dartdoc
        run: dart pub global activate dartdoc

      - name: Build Documentation
        run: rm -rf doc/ && dartdoc --input HookHook.Mobile

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/api
          force_orphan: true
          gh-pages: mobile-doc