name: Mirror Repository

on:
  push:
    branches:
      - '*'

jobs:
  Mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        ref: main

    - name: Mirror to Epitech
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@github.com:EpitechPromo2024/B-YEP-500-NAN-5-1-yearendproject-victor.trencic.git
        ssh_private_key:
            ${{ secrets.SSH_SECRET }}